title: JekyllChess
description: **JekyllChess** is a minimal-CSS Jekyll starter theme for chess blogging. Features figurine notation, FEN (Forsythâ€“Edwards Notation) diagrams, and a simple PGN viewer. Built on **chess.js** and **chessboard.js** libraries.
url: https://jekyllchess.github.io
permalink: /:title.html
exclude:
- README.md
