### your site title here

title: JekyllChess

### exclude the instructions / write-up in the README.md

exclude:
- README.md

plugins:
  - jekyll-remote-theme

remote_theme: http[s]://github.<Enterprise>.com/benbalter/retlab
