title: JekyllChess
description: A Jekyll minimal-CSS starter theme for chess blogging. Features figurine notation, FEN diagrams, and a simple PGN viewer. Built on chess.js and chessboard.js libraries.
url: "https://jekyllrookpawn.github.io"
exclude:
- README.md
