### your site title here

title: JekyllChess

### exclude the instructions / write-up in the README.md

exclude:
- README.md

plugins:
  - jekyll-remote-theme

remote_theme: https://github.com/henrythemes/hello-jekyll-theme
